export const DATOS_LABORALES_COLECCIONES = [
  {
    id: "grupos_de_trabajo",
    collectionName: "grupos_de_trabajo",
    titulo: "grupos_de_trabajo (gdt_*)",
    descripcion: "Unidades del organigrama para dependencia, burbujeo y contexto de ticket.",
    campos: [
      "id",
      "codigo",
      "nombre",
      "parent_group_id",
      "nivel_arbol",
      "activo",
      "vigente_desde",
      "vigente_hasta",
    ],
  },
  {
    id: "cfg_efectores",
    collectionName: "cfg_efectores",
    titulo: "cfg_efectores",
    descripcion: "Catalogo de efectores institucionales para designacion/cumplimiento.",
    campos: [
      "id",
      "codigo",
      "nombre",
      "es_efector_institucional",
      "activo",
      "vigente_desde",
      "vigente_hasta",
    ],
  },
  {
    id: "historial_laboral_cargos",
    collectionName: "historial_laboral_cargos",
    titulo: "historial_laboral_cargos (hlc_*)",
    descripcion: "Cargo base de la persona y referencias a grupo y efectores.",
    campos: [
      "id",
      "persona_id",
      "grupo_de_trabajo_id",
      "efector_designacion_id",
      "efector_cumplimiento_id",
      "carga_horaria_total",
      "vigente_desde",
      "vigente_hasta",
      "activo",
    ],
  },
  {
    id: "historial_laboral_datos",
    collectionName: "historial_laboral_datos",
    titulo: "historial_laboral_datos (hld_*)",
    descripcion: "Nivel 2 del historial laboral para datos complementarios del cargo.",
    campos: [
      "id",
      "cargo_id",
      "persona_id",
      "rol_id",
      "regimen_horario_id",
      "centro_costo_id",
      "escalafon_id",
      "agrupamiento_id",
      "funcion_real_id",
      "muro_id",
      "nivel_jerarquico",
      "fecha_inicio",
      "fecha_fin",
      "activo",
    ],
  },
  {
    id: "historial_laboral_grupos",
    collectionName: "historial_laboral_grupos",
    titulo: "historial_laboral_grupos (hlg_*)",
    descripcion: "Nivel 3: asignacion por grupo y carga por dia para burbuja operativa.",
    campos: [
      "id",
      "dato_laboral_id",
      "persona_id",
      "grupo_de_trabajo_id",
      "nivel_jerarquico",
      "carga_por_dia_semana[]",
      "fecha_inicio",
      "fecha_fin",
      "activo",
    ],
  },
];
