export const PANTALLAS_CATALOGO = [
  { id: "inicio", titulo: "Inicio", path: "/portal/home", estado: "activo", fuente: "web/src/features/home/PortalHome.jsx" },
  { id: "laboral", titulo: "Datos laborales", path: "/portal/laboral", estado: "mvp", fuente: "web/src/pages/DatosLaborales.jsx" },
  { id: "configuracion", titulo: "Configuración", path: "/portal/configuracion", estado: "activo", fuente: "web/src/pages/Configuracion.jsx" },
  { id: "datos-personales", titulo: "Datos personales", path: "/portal/perfil", estado: "mvp", fuente: "web/src/pages/DatosPersonales.jsx" },
  { id: "perfil-legajo", titulo: "Perfil (legajo por id)", path: "/portal/perfil/per_demo", estado: "mvp", fuente: "web/src/pages/Perfil.jsx" },
  { id: "grilla", titulo: "Grilla operativa", path: "/portal/grilla", estado: "borrador", fuente: "web/src/pages/GrillaOperativa.jsx" },
  { id: "onboarding", titulo: "Onboarding wizard", path: "/onboarding", estado: "activo", fuente: "web/src/features/onboarding/OnboardingWizard.jsx" },
  { id: "rrhh-alta", titulo: "RRHH alta agente", path: "/portal/rrhh/alta", estado: "activo", fuente: "web/src/features/rrhh/AltaAgenteRRHH.jsx" },
  {
    id: "rrhh-notif-datos",
    titulo: "RRHH notificaciones datos personales",
    path: "/portal/rrhh/notificaciones-datos-personales",
    estado: "activo",
    fuente: "web/src/pages/NotificacionesEventosDatosPersonalesRRHH.jsx",
  },
  {
    id: "rrhh-seg-enrol",
    titulo: "RRHH seguimiento enrolamiento",
    path: "/portal/rrhh/seguimiento-enrolamiento",
    estado: "activo",
    fuente: "web/src/pages/SeguimientoEnrolamientoUsuariosRRHH.jsx",
  },
  { id: "login", titulo: "Login", path: "/login", estado: "activo", fuente: "web/src/features/auth/LoginRoute.jsx" },
  { id: "registro", titulo: "Registro primer acceso", path: "/login?alta=1", estado: "activo", fuente: "web/src/features/auth/AccesoPortal.jsx" },
  { id: "vinculacion", titulo: "Vinculación por DNI (soporte)", path: "/vinculacion", estado: "activo-soporte", fuente: "web/src/features/auth/VinculacionDni.jsx" },
  { id: "modulos", titulo: "Estado de módulos", path: "/portal/modulos", estado: "activo", fuente: "web/src/pages/EstadoModulos.jsx" },
  { id: "pantallas", titulo: "Catálogo de pantallas", path: "/portal/pantallas", estado: "activo", fuente: "web/src/pages/PantallasCatalogo.jsx" },
];
