export const ESTADO_DDJJ_DEFAULT_PERSONALES = "CFG_DDJJ_01_NO_INICIADA";

export const COLECCIONES_BASE = [
  "personas",
  "formacion_agente",
  "declaraciones_grupo_familiar",
  "consentimientos",
  "eventos_ticket",
];

/** Valores permitidos para `?tipo=` en `/portal/perfil` (selector de colección en UI). */
export const TIPOS_DATOS_PERSONALES_URL = [
  "personas",
  "formacion_agente",
  "declaraciones_grupo_familiar",
  "consentimientos",
];

export const COLECCIONES_CFG = [
  "cfg_estado_civil",
  "cfg_nacionalidad",
  "cfg_sexo_genero",
  "cfg_provincia",
  "cfg_pais",
  "cfg_localidad",
  "cfg_nivel_estudios",
  "cfg_parentesco",
  "cfg_motivo_baja_persona",
  "cfg_estado_declaracion_ddjj",
  "cfg_tipo_consentimiento",
  "cfg_textos_legales",
  "cfg_idioma",
  "cfg_especialidad",
  "cfg_colegio",
  "cfg_jurisdiccion_matricula",
  "cfg_tipo_evento",
  "cfg_estado_bandeja_rrhh",
];

export const HELP = {
  dni: "Documento del agente (solo números).",
  nombre: "Nombre legal del agente.",
  apellido: "Apellido legal del agente.",
  cuil: "CUIL del agente (si está disponible).",
  fecha_nacimiento: "Fecha de nacimiento declarada en ficha personal.",
  nombre_completo_legal: "Se completa automáticamente uniendo nombre y apellido.",
  lugar_nacimiento_id: "Lugar de nacimiento desde catálogo de localidades (opcional).",
  lugar_nacimiento_texto: "Lugar de nacimiento en texto libre (opcional).",
  activo: "Estado operativo de la persona en el padrón RRHH.",
  motivo_baja_id: "Motivo de baja cuando activo=false (catálogo).",
  sexo_genero_id: "Identidad de género del catálogo oficial.",
  estado_civil_id: "Estado civil vigente del catálogo.",
  nacionalidad_id: "Nacionalidad según catálogo.",
  telefono_celular: "Teléfono principal para contacto operativo.",
  email_personal: "Correo personal de contacto (no reemplaza cuenta de acceso).",
  telefono_fijo: "Teléfono fijo de contacto (opcional).",
  recibe_notificaciones_sms: "Indica si habilita notificaciones por WhatsApp.",
  calle: "Calle del domicilio.",
  numero: "Altura / número del domicilio.",
  piso: "Piso del domicilio (opcional).",
  departamento: "Departamento del domicilio (opcional).",
  provincia_id: "Provincia del domicilio.",
  pais_id: "País del domicilio.",
  localidad_id: "Localidad del domicilio (coherente con provincia).",
  codigo_postal: "Código postal del domicilio.",
  referencia: "Referencia para ubicar el domicilio.",
  persona_id: "Identificador per_* del titular.",
  nivel_estudios_id: "Nivel de estudios desde catálogo.",
  titulo_completo: "Título alcanzado.",
  duracion_anios: "Duración total de la carrera/formación.",
  institucion: "Institución donde cursó o egresó.",
  especialidad_id: "Especialidad del agente desde catálogo.",
  colegio_id: "Colegio profesional desde catálogo.",
  matricula_jurisdiccion_id: "Jurisdicción de matrícula desde catálogo.",
  matricula_numero: "Número de matrícula profesional (texto o número según emisor).",
  estado_declaracion_id:
    "Estado DDJJ por catálogo (por defecto: no iniciada hasta presentación/omisión).",
  tipo_consentimiento_id: "Tipo de consentimiento desde catálogo.",
  version_id: "Versión de texto legal (catálogo de textos legales).",
  idioma_id: "Idioma del consentimiento (catálogo).",
  texto_hash: "Hash técnico generado automáticamente desde cfg_textos_legales.",
  foto_archivo: "Foto de rostro (seleccionable desde carpeta o cámara del dispositivo).",
  declaracion_version: "Versión del trámite DDJJ (número).",
  declaracion_jurada_aceptada: "Indica si el titular marcó aceptación de la DDJJ.",
  aceptada_en: "Fecha/hora de aceptación (si aplica).",
  parentesco_id: "Parentesco del familiar desde catálogo.",
  familiar_nombre: "Nombre del familiar declarado.",
  familiar_apellido: "Apellido del familiar declarado.",
  familiar_dni: "DNI del familiar (si corresponde).",
  familiar_fecha_nacimiento: "Fecha de nacimiento del familiar.",
};

export const INITIAL_FORM_DATA_PERSONALES = {
  dni: "",
  nombre: "",
  apellido: "",
  nombre_completo_legal: "",
  cuil: "",
  fecha_nacimiento: "",
  lugar_nacimiento_id: "",
  lugar_nacimiento_texto: "",
  activo: true,
  motivo_baja_id: "",
  sexo_genero_id: "",
  estado_civil_id: "",
  nacionalidad_id: "",
  telefono_celular: "",
  telefono_fijo: "",
  recibe_notificaciones_sms: false,
  email_personal: "",
  calle: "",
  numero: "",
  piso: "",
  departamento: "",
  provincia_id: "",
  pais_id: "",
  localidad_id: "",
  codigo_postal: "",
  referencia: "",
  foto_file: null,
  foto_file_name: "",
  foto_storage_path: "",
  foto_storage_path_thumb: "",
  foto_content_type: "",
  foto_download_url: "",
  persona_id: "",
  nivel_estudios_id: "",
  titulo_completo: "",
  duracion_anios: "",
  institucion: "",
  matricula_numero: "",
  especialidad_id: "",
  colegio_id: "",
  matricula_jurisdiccion_id: "",
  estado_declaracion_id: "",
  declaracion_version: "1",
  declaracion_jurada_aceptada: false,
  consentimiento_evaluacion_rrhh: false,
  ddjj_en_revision: false,
  tipo_consentimiento_id: "",
  version_id: "",
  idioma_id: "",
};
