export const OPCIONES_TIPO_ALTA = [
  { id: "historial_laboral_cargos", nombre: "HLc · historial_laboral_cargos" },
  {
    id: "historial_laboral_grupos",
    nombre: "HLg · historial_laboral_grupos (con vínculo a cargo)",
  },
];

export const COLECCIONES_FORM = [
  "personas",
  "cfg_estado_asignacion_laboral",
  "cfg_escalafon",
  "cfg_agrupamiento",
  "cfg_categorias",
  "cfg_rol",
  "cfg_cargo_funcional",
  "cfg_tipo_vinculo_laboral",
  "cfg_modalidad_jornada",
  "cfg_regimen_horario",
  "cfg_centro_costo",
  "cfg_causal_fin_asignacion_laboral",
  "cfg_motivo_deshabilitacion_hlc",
  "cfg_tipo_acto_designacion",
  "cfg_dia_semana",
];

export const AYUDA_CAMPOS = {
  persona_id: "Identificador único de persona (per_*). Ancla principal del legajo.",
  grupo_de_trabajo_id: "Unidad operativa del organigrama donde se desempeña.",
  efector_designacion_id: "Efector donde fue designado formalmente.",
  efector_cumplimiento_id: "Efector donde cumple funciones efectivamente.",
  estado_asignacion_id: "Estado administrativo actual de la asignación.",
  cargo_funcional_id: "Cargo funcional del puesto (desde catálogo).",
  tipo_vinculo_id: "Tipo de vínculo laboral del cargo según normativa.",
  modalidad_jornada_id: "Modalidad de jornada aplicable al cargo.",
  causal_fin_asignacion_id: "Motivo de finalización; obligatorio cuando se informa fecha_hasta.",
  referencias_normativa_designacion: "Referencia legal del acto de designación del cargo.",
  categoria_id: "Categoría laboral del cargo (desde catálogo).",
  carga_horaria_total: "Carga horaria total del cargo (en horas).",
  computa_antiguedad_licencias:
    "Define si este ciclo HLC se incluye en el cálculo de antigüedad para licencias.",
  fecha_desde: "Fecha de inicio de vigencia del registro.",
  fecha_hasta: "Fecha de fin de vigencia (vacío = abierto).",
  cargo_id: "Referencia al registro HLc base del puesto.",
  rol_id: "Rol de la persona en el cargo base (HLc).",
  regimen_horario_id: "Régimen horario asignado al agente en este grupo (define capa teórica de asistencia).",
  regimen_fecha_ancla: "Día 1 del ciclo para regímenes rotativos. Para fijos/planificados, dejar vacío.",
  centro_costo_id: "Centro de costo o imputación presupuestaria del dato laboral.",
  escalafon_id: "Escalafón administrativo/laboral del cargo.",
  agrupamiento_id: "Agrupamiento laboral del cargo.",
  funcion_real_id: "Función real desempeñada.",
  nivel_jerarquico: "Nivel jerárquico numérico (1 a 99).",
  dato_laboral_id: "Referencia al registro HLd del que depende este subnivel.",
  carga_por_dia_semana: "Carga distribuida por día (seleccionar dia_semana_id + horas por fila).",
};

export const INITIAL_FORM_DATA_LABORAL = {
  persona_id: "",
  grupo_de_trabajo_id: "",
  efector_designacion_id: "",
  efector_cumplimiento_id: "",
  estado_asignacion_id: "",
  carga_horaria_total: "",
  computa_antiguedad_licencias: "si",
  fecha_desde: "",
  fecha_hasta: "",
  cargo_id: "",
  cargo_funcional_id: "",
  tipo_vinculo_id: "",
  modalidad_jornada_id: "",
  causal_fin_asignacion_id: "",
  referencia_tipo_acto_id: "",
  referencia_numero: "",
  referencia_fecha: "",
  referencia_detalle: "",
  categoria_id: "",
  rol_id: "",
  regimen_horario_id: "",
  regimen_fecha_ancla: "",
  centro_costo_id: "",
  escalafon_id: "",
  agrupamiento_id: "",
  funcion_real_id: "",
  nivel_jerarquico: "",
  dato_laboral_id: "",
  carga_por_dia_semana: "",
};
