export const COLECCIONES_FORM = [
  "personas",
  "cfg_estado_asignacion_laboral",
  "cfg_escalafon",
  "cfg_agrupamiento",
  "cfg_categorias",
  "cfg_rol",
  "cfg_cargo_funcional",
  "cfg_tipo_vinculo_laboral",
  "cfg_modalidad_jornada",
  "cfg_regimen_horario",
  "cfg_centro_costo",
  "cfg_causal_fin_asignacion_laboral",
  "cfg_tipo_acto_designacion",
  "cfg_dia_semana",
];

export const AYUDA_CAMPOS = {
  persona_id: "Identificador único de persona (per_*). Ancla principal del legajo.",
  grupo_de_trabajo_id: "Unidad operativa del organigrama donde se desempeña.",
  efector_designacion_id: "Efector donde fue designado formalmente.",
  efector_cumplimiento_id: "Efector donde cumple funciones efectivamente.",
  estado_asignacion_id: "Estado administrativo actual de la asignación.",
  cargo_funcional_id: "Cargo funcional del puesto (desde catálogo).",
  tipo_vinculo_id: "Tipo de vínculo laboral del cargo según normativa.",
  modalidad_jornada_id: "Modalidad de jornada aplicable al cargo.",
  causal_fin_asignacion_id: "Motivo de finalización; obligatorio cuando se informa fecha_hasta.",
  referencias_normativa_designacion: "Referencia legal del acto de designación del cargo.",
  categoria_id: "Categoría laboral del cargo (desde catálogo).",
  carga_horaria_total: "Carga horaria total del cargo (en horas).",
  fecha_desde: "Fecha de inicio de vigencia del registro.",
  fecha_hasta: "Fecha de fin de vigencia (vacío = abierto).",
  cargo_id: "Referencia al registro HLc base del puesto.",
  rol_id: "Rol funcional del agente en ese cargo.",
  regimen_horario_id: "Régimen horario de referencia para procesos futuros (Ticket/RDA/grillas).",
  centro_costo_id: "Centro de costo o imputación presupuestaria del dato laboral.",
  escalafon_id: "Escalafón administrativo/laboral del cargo.",
  agrupamiento_id: "Agrupamiento laboral del cargo.",
  funcion_real_id: "Función real desempeñada.",
  nivel_jerarquico: "Nivel jerárquico numérico (1 a 99).",
  dato_laboral_id: "Referencia al registro HLd del que depende este subnivel.",
  carga_por_dia_semana: "Carga distribuida por día (seleccionar dia_semana_id + horas por fila).",
};
