"use strict";

const MDC_COMANDO_PROYECTAR_PENDIENTE = "PROYECTAR_PENDIENTE";
const MDC_COMANDO_AUTORIZAR_JEFE = "AUTORIZAR_JEFE";
const MDC_COMANDO_CONSOLIDAR_APROBADO = "CONSOLIDAR_APROBADO";
const MDC_COMANDO_REVERTIR_PROYECCION = "REVERTIR_PROYECCION";
const MDC_COMANDO_REINTENTAR_CONSOLIDACION = "REINTENTAR_CONSOLIDACION";

const MDC_COMANDO_VERSION = 1;

const COL_ASISTENCIA_DIARIA = "asistencia_diaria";
const COL_VISTAS_GRILLA_MES = "vistas_grilla_mes_agente";
const COL_MDC_IDEMPOTENCIA = "mdc_comandos_aplicados";

const ESTADO_INSTANCIA_PENDIENTE = "PENDIENTE";
const ESTADO_INSTANCIA_APROBADO = "APROBADO";

const ESTADO_CONSOLIDADO_LABORABLE = "LABORABLE";
const ESTADO_CONSOLIDADO_PENDIENTE_REVISION = "PENDIENTE_REVISION";
const ESTADO_CONSOLIDADO_AUTORIZADO_JEFE = "AUTORIZADO_JEFE";

module.exports = {
  MDC_COMANDO_PROYECTAR_PENDIENTE,
  MDC_COMANDO_AUTORIZAR_JEFE,
  MDC_COMANDO_CONSOLIDAR_APROBADO,
  MDC_COMANDO_REVERTIR_PROYECCION,
  MDC_COMANDO_REINTENTAR_CONSOLIDACION,
  MDC_COMANDO_VERSION,
  COL_ASISTENCIA_DIARIA,
  COL_VISTAS_GRILLA_MES,
  COL_MDC_IDEMPOTENCIA,
  ESTADO_INSTANCIA_PENDIENTE,
  ESTADO_INSTANCIA_APROBADO,
  ESTADO_CONSOLIDADO_LABORABLE,
  ESTADO_CONSOLIDADO_PENDIENTE_REVISION,
  ESTADO_CONSOLIDADO_AUTORIZADO_JEFE,
};
